Update binutils installation

diff --git a/build-fcx-toolchain b/build-fcx-toolchain
--- a/build-fcx-toolchain
+++ b/build-fcx-toolchain
@@ -4,13 +4,13 @@
 # changed for xenon by Felix Domke <tmbinc@elitedvb.net>, still public domain
 # changed for FreeChainXenon by Aiden Isik <aidenisik+git@member.fsf.org>, still public domain
 
-MAIN_TARGET=powerpc64-linux-gnu
-LD_TARGET=i686-w64-mingw32
+TARGET_MAIN=powerpc64-fcx-xenon
+TARGET_PE=powerpc64-fcx-xenonpe
 PREFIX=${PREFIX:-/usr/local/fcx} # Install location of your final toolchain
 PARALLEL=-j$(nproc)
 
 BINUTILS=binutils-2.43.1
-GCC=gcc-14.2.0
+GCC=gcc-dev
 SYNTHXEX=synthxex-0.0.1
 
 # path to the logfile
@@ -44,7 +44,7 @@ function toolchain_install
     # Check if gcc sources are available, download if needed
     if [ ! -d $GCC ]; then
         echo -e "Cloning $GCC"
-	git clone -b $GCC https://git.aidenisik.scot/FreeChainXenon/gcc $GCC || fail_with_info
+	#git clone -b $GCC https://git.aidenisik.scot/FreeChainXenon/gcc $GCC || fail_with_info
     fi
 
     # Check if SynthXEX sources are available, download if needed
@@ -52,23 +52,23 @@ function toolchain_install
 	echo -e "Cloning SynthXEX"
 	git clone -b $SYNTHXEX https://git.aidenisik.scot/FreeChainXenon/SynthXEX $SYNTHXEX || fail_with_info
     fi
-    
+
     rm -rf build
     mkdir build
 
     # Build binutils (main)
     cd build
-    echo -e "Configuring binutils (main/ppc64)..."
-    ../$BINUTILS/configure --target=$MAIN_TARGET --prefix=$PREFIX  --enable-multilib --disable-nls --disable-werror >> $LOGFILE 2>&1 || fail_with_info
-    echo -e "Building binutils (main/ppc64), this could take a while..."
+    echo -e "Configuring binutils..."
+    ../$BINUTILS/configure --target=$TARGET_MAIN --prefix=$PREFIX  --enable-multilib --disable-nls --disable-werror >> $LOGFILE 2>&1 || fail_with_info
+    echo -e "Building binutils (powerpc64-fcx-xenon), this could take a while..."
     make $PARALLEL 2>&1 >> $LOGFILE || fail_with_info
     make install 2>&1 >> $LOGFILE || fail_with_info
     rm -rf *
-
+    
     # Build binutils (PE linker)
     echo -e "Configuring binutils (ld/mingw)..."
-    ../$BINUTILS/configure --target=$LD_TARGET --prefix=$PREFIX/ld  --enable-multilib --disable-nls --disable-werror >> $LOGFILE 2>&1 || fail_with_info
-    echo -e "Building binutils (ld/mingw), this could take a while..."
+    ../$BINUTILS/configure --target=$TARGET_PE --prefix=$PREFIX  --enable-multilib --disable-nls --disable-werror >> $LOGFILE 2>&1 || fail_with_info
+    echo -e "Building binutils (powerpc64-fcx-xenonpe), this could take a while..."
     make $PARALLEL 2>&1 >> $LOGFILE || fail_with_info
     make install 2>&1 >> $LOGFILE || fail_with_info
     cd ..
@@ -86,24 +86,27 @@ function toolchain_install
     echo -e "Done"
 
     # Build GCC.
-    cd build
-    echo -e "Configuring gcc..."
-    ../$GCC/configure --target=$MAIN_TARGET --prefix=$PREFIX --with-libiconv-prefix=/opt/local -enable-interwork \
-	              --enable-languages="c" --without-headers --disable-shared \
-	              --with-newlib --disable-libmudflap --disable-libssp --disable-nls --disable-shared --without-headers \
-	              --disable-decimal-float --enable-altivec\
-	              --with-gmp=/opt/local --with-mpfr=/opt/local --with-cpu=cell >> $LOGFILE 2>&1 || fail_with_info
-    echo -e "Building gcc, this could take a while..."
-    make $PARALLEL all-gcc 2>&1 >> $LOGFILE || fail_with_info
-    make install-gcc 2>&1 >> $LOGFILE || fail_with_info
-    cd ..
-    rm -rf build/*
-    
-    echo -e "Correcting names and moving mingw linker to main directory..."
-    rename 's/powerpc64-linux-gnu/fcx/' $FREECHAINXENON/bin/*
-    cp $PREFIX/ld/bin/i686-w64-mingw32-ld $PREFIX/bin/fcx-ld
-    
-    echo -e "Done"
+    #cd build
+    #echo -e "Configuring gcc..."
+    #../$GCC/configure --target=$TARGET --prefix=$PREFIX --with-libiconv-prefix=/opt/local -enable-interwork \
+#	              --enable-languages="c" --without-headers --disable-shared \
+#	              --with-newlib --disable-libmudflap --disable-libssp --disable-nls --disable-shared --without-headers \
+#	              --disable-decimal-float --enable-altivec\
+#	              --with-gmp=/opt/local --with-mpfr=/opt/local --with-cpu=cell >> $LOGFILE 2>&1 || fail_with_info
+    #echo -e "Building gcc, this could take a while..."
+    #make $PARALLEL all-gcc 2>&1 >> $LOGFILE || fail_with_info
+    #make install-gcc 2>&1 >> $LOGFILE || fail_with_info
+    #cd ..
+    #rm -rf build/*
+
+    #echo -e "Correcting GCC name (temporary)"
+    #rename 's/powerpc64-linux-gnu/powerpc64-fcx-xenon/' $FREECHAINXENON/bin/*
+   
+#    echo -e "Correcting names and moving mingw linker to main directory..."
+#    rename 's/powerpc64-linux-gnu/fcx/' $FREECHAINXENON/bin/*
+#    cp $PREFIX/ld/bin/i686-w64-mingw32-ld $PREFIX/bin/fcx-ld
+#    
+    #echo -e "Done"
 
     rm -rf build
     rm -rf $BINUTILS
